// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: proto/fleet.proto

package fleet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BookingStatus enum
type BookingStatus int32

const (
	BookingStatus_BOOKING_UNKNOWN   BookingStatus = 0
	BookingStatus_BOOKING_CONFIRMED BookingStatus = 1
	BookingStatus_BOOKING_FAILED    BookingStatus = 2
	BookingStatus_BOOKING_EXPIRED   BookingStatus = 3
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_UNKNOWN",
		1: "BOOKING_CONFIRMED",
		2: "BOOKING_FAILED",
		3: "BOOKING_EXPIRED",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_UNKNOWN":   0,
		"BOOKING_CONFIRMED": 1,
		"BOOKING_FAILED":    2,
		"BOOKING_EXPIRED":   3,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fleet_proto_enumTypes[0].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_proto_fleet_proto_enumTypes[0]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{0}
}

// CarStatus represents real-time telemetry from an EV
type CarStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`                        // Unique car identifier
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`                             // Current latitude
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`                           // Current longitude
	BatteryLevel  float64                `protobuf:"fixed64,4,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"` // Battery percentage (0-100)
	Velocity      float64                `protobuf:"fixed64,5,opt,name=velocity,proto3" json:"velocity,omitempty"`                             // Speed in km/h
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                            // Unix timestamp (milliseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarStatus) Reset() {
	*x = CarStatus{}
	mi := &file_proto_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStatus) ProtoMessage() {}

func (x *CarStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStatus.ProtoReflect.Descriptor instead.
func (*CarStatus) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *CarStatus) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *CarStatus) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CarStatus) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CarStatus) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *CarStatus) GetVelocity() float64 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *CarStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// BookingRequest is sent when a car wants to reserve a charging slot
type BookingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CarId           string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`                                // Car making the request
	StationId       string                 `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`                    // Target charging station
	ExpectedArrival int64                  `protobuf:"varint,3,opt,name=expected_arrival,json=expectedArrival,proto3" json:"expected_arrival,omitempty"` // Expected arrival time (Unix timestamp, milliseconds)
	BatteryLevel    float64                `protobuf:"fixed64,4,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`         // Current battery level
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BookingRequest) Reset() {
	*x = BookingRequest{}
	mi := &file_proto_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRequest) ProtoMessage() {}

func (x *BookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRequest.ProtoReflect.Descriptor instead.
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *BookingRequest) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *BookingRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *BookingRequest) GetExpectedArrival() int64 {
	if x != nil {
		return x.ExpectedArrival
	}
	return 0
}

func (x *BookingRequest) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

// BookingResponse is sent back to confirm or deny a booking
type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`    // Unique booking identifier
	CarId         string                 `protobuf:"bytes,2,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`                // Car this response is for
	StationId     string                 `protobuf:"bytes,3,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`    // Assigned station
	Status        BookingStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=fleet.BookingStatus" json:"status,omitempty"` // Status of the booking
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                         // Human-readable message
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // Response timestamp
	PriceRate     float64                `protobuf:"fixed64,7,opt,name=price_rate,json=priceRate,proto3" json:"price_rate,omitempty"`  // Price per kWh at booking time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_proto_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *BookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingResponse) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *BookingResponse) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *BookingResponse) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_UNKNOWN
}

func (x *BookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BookingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BookingResponse) GetPriceRate() float64 {
	if x != nil {
		return x.PriceRate
	}
	return 0
}

// Event messages for Kafka/Redpanda
type TelemetryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	BatteryLevel  float64                `protobuf:"fixed64,4,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	Velocity      float64                `protobuf:"fixed64,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "telemetry", "booking_confirmed", "booking_failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_proto_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryEvent) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *TelemetryEvent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TelemetryEvent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TelemetryEvent) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *TelemetryEvent) GetVelocity() float64 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *TelemetryEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type BookingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	CarId         string                 `protobuf:"bytes,2,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	StationId     string                 `protobuf:"bytes,3,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Status        BookingStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=fleet.BookingStatus" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PriceRate     float64                `protobuf:"fixed64,6,opt,name=price_rate,json=priceRate,proto3" json:"price_rate,omitempty"`
	EventType     string                 `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "booking_confirmed", "booking_failed", "charging_started"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingEvent) Reset() {
	*x = BookingEvent{}
	mi := &file_proto_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingEvent) ProtoMessage() {}

func (x *BookingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingEvent.ProtoReflect.Descriptor instead.
func (*BookingEvent) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *BookingEvent) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingEvent) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *BookingEvent) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *BookingEvent) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_UNKNOWN
}

func (x *BookingEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BookingEvent) GetPriceRate() float64 {
	if x != nil {
		return x.PriceRate
	}
	return 0
}

func (x *BookingEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

var File_proto_fleet_proto protoreflect.FileDescriptor

const file_proto_fleet_proto_rawDesc = "" +
	"\n" +
	"\x11proto/fleet.proto\x12\x05fleet\"\xbb\x01\n" +
	"\tCarStatus\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12#\n" +
	"\rbattery_level\x18\x04 \x01(\x01R\fbatteryLevel\x12\x1a\n" +
	"\bvelocity\x18\x05 \x01(\x01R\bvelocity\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x96\x01\n" +
	"\x0eBookingRequest\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tR\tstationId\x12)\n" +
	"\x10expected_arrival\x18\x03 \x01(\x03R\x0fexpectedArrival\x12#\n" +
	"\rbattery_level\x18\x04 \x01(\x01R\fbatteryLevel\"\xeb\x01\n" +
	"\x0fBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x15\n" +
	"\x06car_id\x18\x02 \x01(\tR\x05carId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x03 \x01(\tR\tstationId\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.fleet.BookingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"price_rate\x18\a \x01(\x01R\tpriceRate\"\xdf\x01\n" +
	"\x0eTelemetryEvent\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12#\n" +
	"\rbattery_level\x18\x04 \x01(\x01R\fbatteryLevel\x12\x1a\n" +
	"\bvelocity\x18\x05 \x01(\x01R\bvelocity\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\"\xed\x01\n" +
	"\fBookingEvent\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x15\n" +
	"\x06car_id\x18\x02 \x01(\tR\x05carId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x03 \x01(\tR\tstationId\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.fleet.BookingStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"price_rate\x18\x06 \x01(\x01R\tpriceRate\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType*d\n" +
	"\rBookingStatus\x12\x13\n" +
	"\x0fBOOKING_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11BOOKING_CONFIRMED\x10\x01\x12\x12\n" +
	"\x0eBOOKING_FAILED\x10\x02\x12\x13\n" +
	"\x0fBOOKING_EXPIRED\x10\x032O\n" +
	"\fFleetService\x12?\n" +
	"\x0fStreamTelemetry\x12\x10.fleet.CarStatus\x1a\x16.fleet.BookingResponse(\x010\x01B\"Z github.com/greenlane/proto/fleetb\x06proto3"

var (
	file_proto_fleet_proto_rawDescOnce sync.Once
	file_proto_fleet_proto_rawDescData []byte
)

func file_proto_fleet_proto_rawDescGZIP() []byte {
	file_proto_fleet_proto_rawDescOnce.Do(func() {
		file_proto_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fleet_proto_rawDesc), len(file_proto_fleet_proto_rawDesc)))
	})
	return file_proto_fleet_proto_rawDescData
}

var file_proto_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_fleet_proto_goTypes = []any{
	(BookingStatus)(0),      // 0: fleet.BookingStatus
	(*CarStatus)(nil),       // 1: fleet.CarStatus
	(*BookingRequest)(nil),  // 2: fleet.BookingRequest
	(*BookingResponse)(nil), // 3: fleet.BookingResponse
	(*TelemetryEvent)(nil),  // 4: fleet.TelemetryEvent
	(*BookingEvent)(nil),    // 5: fleet.BookingEvent
}
var file_proto_fleet_proto_depIdxs = []int32{
	0, // 0: fleet.BookingResponse.status:type_name -> fleet.BookingStatus
	0, // 1: fleet.BookingEvent.status:type_name -> fleet.BookingStatus
	1, // 2: fleet.FleetService.StreamTelemetry:input_type -> fleet.CarStatus
	3, // 3: fleet.FleetService.StreamTelemetry:output_type -> fleet.BookingResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_fleet_proto_init() }
func file_proto_fleet_proto_init() {
	if File_proto_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fleet_proto_rawDesc), len(file_proto_fleet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fleet_proto_goTypes,
		DependencyIndexes: file_proto_fleet_proto_depIdxs,
		EnumInfos:         file_proto_fleet_proto_enumTypes,
		MessageInfos:      file_proto_fleet_proto_msgTypes,
	}.Build()
	File_proto_fleet_proto = out.File
	file_proto_fleet_proto_goTypes = nil
	file_proto_fleet_proto_depIdxs = nil
}
