# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fleet_pb2 as fleet__pb2


class FleetServiceStub(object):
    """Service definition for bidirectional streaming between EVs and the ingestion service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_stream(
                '/fleet.FleetService/StreamTelemetry',
                request_serializer=fleet__pb2.CarStatus.SerializeToString,
                response_deserializer=fleet__pb2.BookingResponse.FromString,
                )


class FleetServiceServicer(object):
    """Service definition for bidirectional streaming between EVs and the ingestion service
    """

    def StreamTelemetry(self, request_iterator, context):
        """Bidirectional stream: EVs send telemetry, server sends booking confirmations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=fleet__pb2.CarStatus.FromString,
                    response_serializer=fleet__pb2.BookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.FleetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FleetService(object):
    """Service definition for bidirectional streaming between EVs and the ingestion service
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/fleet.FleetService/StreamTelemetry',
            fleet__pb2.CarStatus.SerializeToString,
            fleet__pb2.BookingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
