# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fleet.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66leet.proto\x12\x05\x66leet\"|\n\tCarStatus\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x15\n\rbattery_level\x18\x04 \x01(\x01\x12\x10\n\x08velocity\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"e\n\x0e\x42ookingRequest\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\t\x12\x12\n\nstation_id\x18\x02 \x01(\t\x12\x18\n\x10\x65xpected_arrival\x18\x03 \x01(\x03\x12\x15\n\rbattery_level\x18\x04 \x01(\x01\"\xa7\x01\n\x0f\x42ookingResponse\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61r_id\x18\x02 \x01(\t\x12\x12\n\nstation_id\x18\x03 \x01(\t\x12$\n\x06status\x18\x04 \x01(\x0e\x32\x14.fleet.BookingStatus\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x12\n\nprice_rate\x18\x07 \x01(\x01\"\x95\x01\n\x0eTelemetryEvent\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x15\n\rbattery_level\x18\x04 \x01(\x01\x12\x10\n\x08velocity\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x12\n\nevent_type\x18\x07 \x01(\t\"\xa7\x01\n\x0c\x42ookingEvent\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61r_id\x18\x02 \x01(\t\x12\x12\n\nstation_id\x18\x03 \x01(\t\x12$\n\x06status\x18\x04 \x01(\x0e\x32\x14.fleet.BookingStatus\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x12\n\nprice_rate\x18\x06 \x01(\x01\x12\x12\n\nevent_type\x18\x07 \x01(\t*d\n\rBookingStatus\x12\x13\n\x0f\x42OOKING_UNKNOWN\x10\x00\x12\x15\n\x11\x42OOKING_CONFIRMED\x10\x01\x12\x12\n\x0e\x42OOKING_FAILED\x10\x02\x12\x13\n\x0f\x42OOKING_EXPIRED\x10\x03\x32O\n\x0c\x46leetService\x12?\n\x0fStreamTelemetry\x12\x10.fleet.CarStatus\x1a\x16.fleet.BookingResponse(\x01\x30\x01\x42\"Z github.com/greenlane/proto/fleetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fleet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/greenlane/proto/fleet'
  _globals['_BOOKINGSTATUS']._serialized_start=743
  _globals['_BOOKINGSTATUS']._serialized_end=843
  _globals['_CARSTATUS']._serialized_start=22
  _globals['_CARSTATUS']._serialized_end=146
  _globals['_BOOKINGREQUEST']._serialized_start=148
  _globals['_BOOKINGREQUEST']._serialized_end=249
  _globals['_BOOKINGRESPONSE']._serialized_start=252
  _globals['_BOOKINGRESPONSE']._serialized_end=419
  _globals['_TELEMETRYEVENT']._serialized_start=422
  _globals['_TELEMETRYEVENT']._serialized_end=571
  _globals['_BOOKINGEVENT']._serialized_start=574
  _globals['_BOOKINGEVENT']._serialized_end=741
  _globals['_FLEETSERVICE']._serialized_start=845
  _globals['_FLEETSERVICE']._serialized_end=924
# @@protoc_insertion_point(module_scope)
